### ISSUE TITLE
face_reco_from_camera_single_face.py 問題

### ISSUE THREAD

**Issue by u1010843** [coneypo/Dlib_face_recognition_from_camera#50] opened 2022-02-19 18:57 UTC
想詢問，訓練完人臉後，使用face_reco_from_camera有正常辨識出人臉，但是使用face_reco_from_camera_single_face時卻始終顯示成張三，我看可能的問題出現在def draw_name內的self.current_frame_face_position_list直接被定義在[1]，而face_reco_from_camera的def draw_name內的self.current_frame_face_position_list有使用for迴圈計算，請問作者方便告訴我該如何修正嗎?謝謝您

**Comment by coneypo** [comment] 2022-04-27 12:38
Sorry, cannot reproduct this issue when using "xxx_single_face.py";
For example:
1. Frame N: person_1 -> jacky
2. Frame N+1: no faces
3. Frame N+2: person_2 -> unknow, so it will always be "jacky" for you, right?
Maybe you can print more log inside it to check this issue;

BTW, when using "xxx_single_face.py", max faces <=1, so we needn't "for" loop to check `current_frame_face_position_list`, because the max size of it is 1;

**Comment by coneypo** [comment] 2022-07-04 15:11
I will close this issue if no more problem

**Closed** 2022-11-05 06:40 UTC
